// <auto-generated />
namespace FinalExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nika3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nika3));
        
        string IMigrationMetadata.Id
        {
            get { return "202001210744487_nika3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
